CXX_OPTS=-Wall -fPIC -O3 -g -std=c++11 -I..
LD_OPTS=-O3 -g -fPIC
CXX=g++
CC=gcc

ifndef VPI_USER_H_DIR
	VPI_USER_H_DIR=/usr/local/Altera/14.1/modelsim_ase/include
endif

ifndef BLUESPECDIR
	BLUESPECDIR=/usr/local/Bluespec/lib
endif

unittest: Test_BDPIPipe_Unit
	./Test_BDPIPipe_Unit

Test_BDPIPipe_Unit: Test_BDPIPipe_Unit.o
	$(CXX) $(LD_OPTS) -o $@ $^ -lboost_unit_test_framework -lgmp

%.o: Streams/%.cpp *.hpp
	$(CXX) $(CXX_OPTS) -c $<
	
%.o: %.cpp *.hpp BitPackUnpack/*.hpp BitPackUnpack/Types/*.hpp
	$(CXX) $(CXX_OPTS) -c $<

%_32.o: Streams/%.cpp *.hpp
	$(CXX) $(CXX_OPTS) -m32 -c $<
	mv $*.o $@
	
%_32.o: %.cpp *.hpp
	$(CXX) $(CXX_OPTS) -m32 -c $< 
	mv $*.o $@

clean:
	rm -rf *.so *.o test model_*.[ch] model_*.cxx *.out *.b[ao] *.dSYM mkTB_*.cxx mkTB_*.h vpi_wrapper* imported_BDPI_functions.h \
		Test_BDPIPipe Test_BDPIPipe_Unit test-BDPIPipe register.c BDPIPipe_register.c mk*.v work

test-BDPIPipe: Test_BDPIPipe.bsv BDPIPipe.bsv libBDPIPipe.so
	bsc -u -sim -check-assert $<
	bsc -sim -g mkTB_All $<
	bsc -sim -e mkTB_All -o $@ -L . -l BDPIPipe


# Bluespec generates wrapper files that must be compiled to register with VPI for Verilog simulation
# This script just generates a wrapper that will register all of them
BDPIPipe_register.c mkTB_All.v: Test_BDPIPipe.bsv
	bsc -verilog -u -check-assert $<
	bsc -verilog -g mkTB_All -o mkTB_All.v $<
	echo "// Automatically generated by Makefile" > $@
	for i in `ls vpi_wrapper_*.h`; do echo "#include \"$$i\"" >> $@ ; done;
	echo "void (*vlog_startup_routines[])() = { " >> $@
	echo "`ls vpi_wrapper_*.h`" | sed -ne "s/vpi_wrapper_\(.*\)\.h/\1_vpi_register, /p" >> $@
	echo "0u }; " >> $@

# Compile the BDPI Stream functions (32b for linking to Modelsim)
libBDPIPipe_32.so: mersenne19937_32.o add_18b_4b_32.o BDPIStreams_32.o
	$(CXX) $(LD_OPTS) -shared -m32 -o $@ $^ -lgmp

# Compile the VPI registration functions (32bit version for Modelsim)
libBDPIPipe_VPI32.so: BDPIPipe_register.c libBDPIPipe_32.so
	$(CC) $(LD_OPTS) -shared -m32 -o $@ -I$(VPI_USER_H_DIR) -I$(BLUESPECDIR)/VPI vpi_wrapper_*.c $< -L. -L$(BLUESPECDIR)/VPI/g++4 -lBDPIPipe_32 -lbdpi

verilog: libBDPIPipe_VPI32.so libBDPIPipe_32.so mkTB_All.v

verilog-sim: verilog
	vlib work
	vlog -timescale 1ns/1ns +define+BSV_ASSIGNMENT_DELAY=\#1 mkTB_All.v $(BLUESPECDIR)/Verilog/RevertReg.v
	vsim -do "testAll.tcl" -c

libBDPIPipe_VPI.so: BDPIPipe_register32.o libBDPIPipe.so
	$(CXX) $(LD_OPTS) -shared -o $@ $< -lBDPIPipe
	
libBDPIPipe.so: mersenne19937.o add_18b_4b.o BDPIStreams.o
	$(CXX) $(LD_OPTS) -shared -o $@ $^ -lgmp
